services:
  survey:
    build:
      context: docker
      dockerfile: Dockerfile-dev
    pull_policy: never
    image: barthjs/survey:dev
    container_name: survey
    ports:
      - 80:80
      - 5173:5173
    volumes:
      - ./:/app
    extra_hosts:
      - host.docker.internal:host-gateway

  database:
    image: postgres:18-alpine
    container_name: survey-db
    working_dir: /pgsqldump
    ports:
      - 5432:5432
    volumes:
      - ./database:/pgsqldump
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  db:
