# Base image with PHP and nginx
FROM webdevops/php-nginx-dev:8.3-alpine

ARG VERSION=dev
ENV APP_VERSION=${VERSION} \
    PHP_DEBUGGER=xdebug \
    PHP_DISPLAY_ERRORS=1 \
    PHP_IDE_CONFIG="serverName=survey" \
    WEB_DOCUMENT_ROOT=/app/public \
    XDEBUG_CLIENT_HOST=host.docker.internal \
    XDEBUG_CLIENT_PORT=9003 \
    XDEBUG_START_WITH_REQUEST=yes

LABEL org.opencontainers.image.title="Survey" \
      org.opencontainers.image.description="Survey creation tool" \
      org.opencontainers.image.url="https://github.com/barthjs/survey" \
      org.opencontainers.image.source="https://github.com/barthjs/survey" \
      org.opencontainers.image.version=${VERSION} \
      org.opencontainers.image.licenses="MIT"

# Install build dependencies
RUN apk add --no-cache sqlite-dev nodejs npm

WORKDIR /app
